#!/bin/bash
"""
Auto-commit healed Terraform files with audit trail.
"""

set -e

COMMIT_MSG="${1:-[AUTO-HEAL] Fix Terraform formatting}"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

echo "Current branch: $BRANCH_NAME"
echo "Checking for modified files..."

# Stage all Terraform file changes
if git diff --quiet terraform/ 2>/dev/null || [ ! -d terraform/ ]; then
    echo "No Terraform changes detected. Skipping commit."
    exit 0
fi

git add -A terraform/ .github/workflows/ scripts/

# Show what will be committed
echo "Files staged for commit:"
git diff --cached --name-only

# Commit with audit trail
git config user.email "terraform-bot@github.local"
git config user.name "Terraform Auto-Heal Bot"

git commit -m "$COMMIT_MSG" -m "Auto-generated by Terraform fmt self-heal pipeline" || {
    echo "No changes to commit (already formatted)."
    exit 0
}

# Force push if on auto-heal branch, otherwise just push
if [[ $BRANCH_NAME == *"auto-heal"* ]]; then
    git push origin "$BRANCH_NAME" --force
else
    git push origin "$BRANCH_NAME" || {
        echo "Warning: Could not push changes. Manual push may be required."
        exit 0
    }
fi

echo "✓ Auto-heal commit pushed successfully"
