#!/usr/bin/env bash
# Create a branch with healed .tf files, push, and open a PR to BASE_BRANCH.
# Requires: gh, git, GH_TOKEN (or GITHUB_TOKEN). Env: BASE_BRANCH, HEAL_BRANCH, COMMIT_MSG.

set -euo pipefail

BASE_BRANCH="${BASE_BRANCH:?BASE_BRANCH is required}"
HEAL_BRANCH="${HEAL_BRANCH:?HEAL_BRANCH is required}"
COMMIT_MSG="${COMMIT_MSG:-[AUTO-HEAL] Fix Terraform formatting}"
REPO="${GITHUB_REPOSITORY:-}"
RUN_URL="${GITHUB_SERVER_URL:-https://github.com}/${REPO}/actions/runs/${GITHUB_RUN_ID:-}"

git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git config user.name "github-actions[bot]"

mapfile -t tf_files < <(git ls-files -m -o --exclude-standard | grep '\.tf$' || true)
if [[ ${#tf_files[@]} -eq 0 ]]; then
  echo "No modified or untracked .tf files to publish."
  exit 0
fi

git checkout -b "$HEAL_BRANCH"
git add -- "${tf_files[@]}"
if git diff --cached --quiet; then
  echo "Nothing staged after git add; skipping push."
  exit 0
fi

git commit -m "$COMMIT_MSG" -m "Auto-generated by Terraform fmt self-heal workflow." \
  -m "Workflow run: $RUN_URL"

git push -u origin "$HEAL_BRANCH"

pr_body_file=/tmp/auto_heal_pr_body.md
{
  echo "## Terraform format auto-heal"
  echo
  echo "This pull request was opened automatically after \`terraform fmt --check\` failed on **${BASE_BRANCH}** and Claude applied formatting-only fixes."
  echo
  echo "- **Workflow run:** ${RUN_URL}"
  if [[ -f /tmp/claude_heal_report.json ]]; then
    echo
    echo "### Claude heal report (machine-readable)"
    echo
    echo '```json'
    cat /tmp/claude_heal_report.json
    echo
    echo '```'
  fi
  if [[ -f /tmp/fmt_output.txt ]]; then
    echo
    echo "### Original \`terraform fmt --check\` output"
    echo
    echo '```text'
    head -c 16000 /tmp/fmt_output.txt || true
    echo
    echo '```'
  fi
} >"$pr_body_file"

pr_url="$(gh pr create \
  --repo "$REPO" \
  --base "$BASE_BRANCH" \
  --head "$HEAL_BRANCH" \
  --title "chore(terraform): auto-heal formatting (run ${GITHUB_RUN_ID:-unknown})" \
  --body-file "$pr_body_file")"

echo "$pr_url" >/tmp/pr_url.txt
echo "Opened pull request: $pr_url"
